<%@ Page Title="Tin Tức" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="tintuc.aspx.cs" Inherits="voleyballnews.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <h1 class="title-detail" itemprop="headline" style="box-sizing: border-box; font-size: 20px; margin: 20px 0px 10px; font-family: arial; font-weight: bold; line-height: 28px; color: rgb(40, 40, 40); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Bóng chuyền nam Thái Lan trở thành cựu vương, Philippines vào chung kết</h1>
    <p class="title-detail" itemprop="headline" style="box-sizing: border-box; font-size: 20px; margin: 20px 0px 10px; font-family: arial; font-weight: bold; line-height: 28px; color: rgb(40, 40, 40); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image1" runat="server" ImageUrl="~/image/c894df42aa06fcb0e8e3ff55b71b33fd.jpg" />
    </p>
    <p class="title-detail" itemprop="headline" style="box-sizing: border-box; font-size: 20px; margin: 20px 0px 10px; font-family: arial; font-weight: bold; line-height: 28px; color: rgb(40, 40, 40); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <em style="box-sizing: border-box; color: rgb(98, 98, 98); font-family: arial; font-size: 13px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bold;">Bagunas là mũi tấn công nguy hiểm nhất của bóng chuyền nam Philippines.</strong></em></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(98, 98, 98); font-family: arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
        Bóng chuyền nam Philippines đang mạnh lên và những chiến thắng tại vòng bảng của họ thực sự không phải là ăn may. Chủ công Bagunas thực sự là mũi tấn công lợi hại khi chơi rất toàn diện cả trong những tình huống tấn công hay khả năng chuyền một phòng thủ. Chính tay đập này như tiếp thêm động lực để các VĐV của Philippines chơi tự tin và thăng hoa.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(98, 98, 98); font-family: arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
        Như thường lệ Thái Lan luôn thể hiện là đội bóng cửa trên khi thể hiện lối đánh phủ đầu khi có chiến thắng nhanh 25-17. Thế nhưng, Philippines chơi quá thăng hoa, trước sự cổ vũ của các khán giả nhà họ chơi ăn miếng trả miếng khi san hòa 25-20 trong sét đấu thứ 2. Hai đội thể hiện sự ngang tài, ngang sức khi chia đều chiến thắng ở sét thứ 3 và 4 đẩy trận đấu vào sét 5 quyết định. Nhưng phải nói rằng Bagunas đã chơi quá hay, khi giúp Philippines chiến thắng 17-15 đẩy Thái Lan trở thành nhà cựu vô địch của giải đấu.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(98, 98, 98); font-family: arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
        Đây có thể coi là chiến thắng lịch sử của bóng chuyền nam Philippines bởi trong suốt 42 năm lịch sử của SEA Games kể từ năm 1977. Bóng chuyền nam Philippines chưa một lần bước được vào chơi ở trận chung kết. Còn với bóng chuyền nam Thái Lan, lần gần nhất họ phải vào tranh tấm HCĐ là năm 2007.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(98, 98, 98); font-family: arial; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
        Có thể thấy rằng, dù đội hình nào của bóng chuyền nam Việt Nam tham dự SEA Games 30 thì cũng sẽ trắng tay. Bởi từ thực tế đang diễn ra có thể thấy, các quốc gia khác trong khu vực đang có sự tập trung và đầu tư rất tốt cho môn bóng chuyền nam.</p>
    <p class="title-detail" itemprop="headline" style="box-sizing: border-box; font-size: 20px; margin: 20px 0px 10px; font-family: arial; font-weight: bold; line-height: 28px; color: rgb(40, 40, 40); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
</asp:Content>
